// src/app/metadata.ts
// src/app/metadata.ts

export const getMetadata = (pageTitle: string) => {
    return {
      title: pageTitle,
      description: "Generated by create next app",
      // Otros metadatos que puedas necesitar
    };
  };
  
